### PR TITLE
Update plugin portal badge

### PR DESCRIPTION
**Pull request by runningcode**
Check it [here](https://github.com/gradle/gradle-enterprise-build-config-samples/tree/no/plugin-portal-badge/common-custom-user-data-gradle-plugin)

### CODE REVIEW

**Review by etiennestuder — CHANGES_REQUESTED** [review]
Can you change the badge label to 'Plugin Portal' please?

**Review by marcphilipp — CHANGES_REQUESTED** [review]
Looks like this for me:
Screenshot 2021-01-20 at 18 01 47

Maybe the space in the URL needs to be replaced with `%20`?

**Comment by runningcode** [comment]
@marcphilipp woops, thanks for catching. fixed.

**Review by marcphilipp — APPROVED** [review]

**Comment by etiennestuder** [comment]
@runningcode You can merge it as soon as it is fully working, without a firther review from me.

**Pull request merged**
